schedule: every day
branch: develop
label_prs: update
branch_prefix: hotfix/
assignees:
 - juliomrqz
 - giovagnoli

requirements:
  - backend/requirements/local.txt:
      update: all
  - backend/requirements/base.txt:
      update: all
  - backend/requirements/production.txt:
      update: insecure
